"""Added default

Revision ID: 294ccc05f445
Revises: f6b8761bfcbc
Create Date: 2020-04-26 13:26:17.189418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294ccc05f445'
down_revision = 'f6b8761bfcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_rating', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_rating', 'rating')
    # ### end Alembic commands ###
