"""Initial migration.

Revision ID: 628d6e19ab7e
Revises: 
Create Date: 2020-04-26 12:52:52.010717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628d6e19ab7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('book', 'rating')
    op.drop_column('book', 'reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('reviews', sa.INTEGER(), nullable=True))
    op.add_column('book', sa.Column('rating', sa.INTEGER(), nullable=True))
    op.drop_table('book_rating')
    # ### end Alembic commands ###
