"""Added Ratings

Revision ID: f6b8761bfcbc
Revises: 628d6e19ab7e
Create Date: 2020-04-26 13:23:24.649582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b8761bfcbc'
down_revision = '628d6e19ab7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_rating', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_rating', 'rating')
    # ### end Alembic commands ###
