"""empty message

Revision ID: f838a5a14976
Revises: 294ccc05f445
Create Date: 2020-04-26 13:28:36.631697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f838a5a14976'
down_revision = '294ccc05f445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_rating', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_rating', 'rating')
    # ### end Alembic commands ###
